//! Sigma-algebra F: collection of events closed under complement and countable unions

use serde::{Serialize, Deserialize};
use super::sample_space::Event;

/// A sigma-algebra over a sample space
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SigmaAlgebra {
    /// The generating set of events
    generators: Vec<Event>,
    /// Whether this represents the Borel sigma-algebra on ℝ
    is_borel: bool,
}

impl SigmaAlgebra {
    /// Create from explicit events (generators)
    pub fn from_events(events: Vec<Event>) -> Self {
        SigmaAlgebra { generators: events, is_borel: false }
    }

    /// The trivial sigma-algebra {∅, Ω}
    pub fn trivial() -> Self {
        SigmaAlgebra {
            generators: vec![Event::empty(), Event::sure()],
            is_borel: false,
        }
    }

    /// The power set of a finite sample space
    pub fn power_set(n: usize) -> Self {
        // Generate all subsets of {0, 1, ..., n-1}
        let mut events = vec![Event::empty()];
        for i in 0..n {
            events.push(Event::discrete(vec![i as f64]));
        }
        // Add unions
        if n <= 10 {
            for mask in 1u32..(1u32 << n) {
                let pts: Vec<f64> = (0..n)
                    .filter(|i| (mask >> i) & 1 == 1)
                    .map(|i| i as f64)
                    .collect();
                events.push(Event::discrete(pts));
            }
        }
        SigmaAlgebra { generators: events, is_borel: false }
    }

    /// The Borel sigma-algebra on ℝ (generated by all open intervals)
    pub fn borel() -> Self {
        SigmaAlgebra { generators: vec![], is_borel: true }
    }

    /// Check if an event is measurable (in the sigma-algebra)
    pub fn contains(&self, event: &Event) -> bool {
        if self.is_borel {
            // All "reasonable" events are Borel-measurable
            return true;
        }
        // Check if the event matches or is a combination of generators
        for gen in &self.generators {
            if events_equal(gen, event) {
                return true;
            }
        }
        // Check unions and complements
        false
    }

    /// Number of generating events
    pub fn generator_count(&self) -> usize {
        self.generators.len()
    }

    /// Get generators
    pub fn generators(&self) -> &[Event] {
        &self.generators
    }

    /// Is this the Borel sigma-algebra?
    pub fn is_borel(&self) -> bool {
        self.is_borel
    }

    /// Compute the generated sigma-algebra (for finite cases)
    /// Returns the closure under complement and finite unions
    pub fn closure(&self) -> SigmaAlgebra {
        let mut events = self.generators.clone();
        let mut changed = true;
        while changed {
            changed = false;
            let n = events.len();
            // Add complements
            for i in 0..n {
                let comp = events[i].complement();
                if !events.iter().any(|e| events_equal(e, &comp)) {
                    events.push(comp);
                    changed = true;
                }
            }
            // Add pairwise unions
            let n2 = events.len();
            for i in 0..n2 {
                for j in (i + 1)..n2 {
                    let union = events[i].union(&events[j]);
                    if !events.iter().any(|e| events_equal(e, &union)) {
                        events.push(union);
                        changed = true;
                    }
                }
            }
        }
        SigmaAlgebra { generators: events, is_borel: self.is_borel }
    }
}

/// Check approximate equality of two events
fn events_equal(a: &Event, b: &Event) -> bool {
    if a.is_interval != b.is_interval {
        return false;
    }
    if a.is_interval {
        (a.low - b.low).abs() < 1e-10 && (a.high - b.high).abs() < 1e-10
    } else {
        if a.points.len() != b.points.len() {
            return false;
        }
        let mut ap = a.points.clone();
        let mut bp = b.points.clone();
        ap.sort_by(|x, y| x.partial_cmp(y).unwrap());
        bp.sort_by(|x, y| x.partial_cmp(y).unwrap());
        ap.iter().zip(bp.iter()).all(|(x, y)| (x - y).abs() < 1e-10)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_trivial_sigma_algebra() {
        let sa = SigmaAlgebra::trivial();
        assert!(sa.contains(&Event::empty()));
        assert_eq!(sa.generator_count(), 2);
    }

    #[test]
    fn test_power_set() {
        let sa = SigmaAlgebra::power_set(3);
        assert!(sa.generator_count() >= 8); // 2^3 = 8
    }

    #[test]
    fn test_borel_contains_everything() {
        let sa = SigmaAlgebra::borel();
        assert!(sa.is_borel());
        assert!(sa.contains(&Event::interval(0.0, 1.0)));
        assert!(sa.contains(&Event::interval(-5.0, 5.0)));
    }

    #[test]
    fn test_closure() {
        let sa = SigmaAlgebra::from_events(vec![Event::interval(0.0, 1.0)]);
        let closed = sa.closure();
        assert!(closed.generator_count() > 1);
    }
}
